Rework tag buttons - new icons + "edit tag" button
ezra-bible-app/ezra-bible-app pull request #531
Opened 2021-11-20 09:16 UTC by tobias-klein

This closes #475.

The changes are rather simple and the primary target is to have a more accessible rename function for touch screens.
This is just a first step. A second step can be implemented based on #530.

* A fixed edit tag button was added to replace the mouseover "rename tag" functionality.
* The delete icon has been replaced with the trashbin icon.

This is how it looks:
![image](https://user-images.githubusercontent.com/17739895/142721024-55d72de3-ac01-4ceb-bcfe-107f4061c31c.png)

2021-11-23 14:16 UTC, zhuiks commented
@tobias-klein can you move tag-edit and tag-delete buttons after tag name and numbers.
So the first user attention will be on actual tag name instead of trash icon.

2021-11-23 17:14 UTC, tobias-klein commented
> @tobias-klein can you move tag-edit and tag-delete buttons after tag name and numbers.
> So the first user attention will be on actual tag name instead of trash icon.

Good point. Do you have a CSS tip how this could be done while keeping the icons in "columns"?

2021-11-25 09:07 UTC, tobias-klein commented
@zhuiks 
I moved the buttons to the right side.

![image](https://user-images.githubusercontent.com/17739895/143412039-34bc2dc9-6842-4fbe-9f33-55f700eda1ab.png)

With this it's a bit hard to the relationship between the buttons and the tag on the left side, maybe we should introduce alternating background colors for the items in the tag list?

2021-11-25 09:32 UTC, tobias-klein commented
This is the latest variant with alternating background colors.

![image](https://user-images.githubusercontent.com/17739895/143415791-261d6693-69a6-4dd1-9952-402fdcd01786.png)

![image](https://user-images.githubusercontent.com/17739895/143416010-2fc963ec-cb2e-4c90-b06b-01f0213dea26.png)

2021-11-26 14:03 UTC, zhuiks requested changes
Buttons can be styled differently. Smaller border radius, and just border without background.
But I can do it in or after #526. I think styling should be similar to side-panel buttons. 

Is there enough spacing between edit and delete buttons on the tablet?

So my only suggestion for this PR is to use CSS var for odd rows background.

2021-11-27 02:38 UTC, zhuiks submitted a review, later dismissed

2021-11-27 07:52 UTC, tobias-klein commented
> Buttons can be styled differently. Smaller border radius, and just border without background. But I can do it in or after #526. I think styling should be similar to side-panel buttons.

Let's change that separately.

> 
> Is there enough spacing between edit and delete buttons on the tablet?

Yes, I think so.

> 
> So my only suggestion for this PR is to use CSS var for odd rows background.

Done!

2021-11-27 07:53 UTC, tobias-klein commented on css/toolbox.css
> +  background: lightgray;
Done

2021-11-27 08:42 UTC, merged