Support apocryphal books
ezra-bible-app/ezra-bible-app pull request #613
Opened 2022-02-06 13:20 UTC by tobias-klein

This PR fixes #612.

To test this, install one of the following modules:

* KJVA (English)
* engRV1895eb (English)
* engasvbt2021eb (English)
* Vulgate (Latin)

2022-02-10 02:04 UTC, zhuiks requested changes
Nice!

I notice a few things on the UI side:

- Somehow I can switch from translation with apocryphal books to canonical only translation:
![Screenshot from 2022-02-09 19-44-55](https://user-images.githubusercontent.com/3584119/153322917-93e8b09b-68ca-4080-8805-5d0caabbc2e5.png)

- Seems like headers are not always displayed correctly:
![Screenshot from 2022-02-09 19-58-00](https://user-images.githubusercontent.com/3584119/153323063-400bfc29-374d-4f70-b0a6-2dacfe2d009d.png)

Let me know if I need to provide more concrete steps to reproduce.

2022-02-12 07:35 UTC, tobias-klein commented on app/frontend/helpers/sword_module_helper.js
> +  for (let i = 0; i < books.length; i++) {
Good point! This is more significant on Android! I will look into it.

2022-02-12 07:47 UTC, tobias-klein commented
> * Seems like headers are not always displayed correctly:

This was a bug in node-sword-interface, but I had fixed it. Did you run `npm install` after switching to the branch?

2022-02-12 07:50 UTC, tobias-klein commented
> * Somehow I can switch from translation with apocryphal books to canonical only translation:

This bug was already existing before. When you have opened a book in the OT for example, it is still possible to switch to a translation that does not contain OT books. I have now opened issue #616 for it.

2022-02-12 08:42 UTC, tobias-klein commented on app/frontend/helpers/sword_module_helper.js
> +  for (let i = 0; i < books.length; i++) {
This is fixed now.

2022-02-12 08:43 UTC, tobias-klein commented
@zhuiks Can you test once more with the latest changes (ensure to run `npm install` as well) and then approve if everything is fine?

2022-02-17 01:10 UTC, zhuiks approved these changes
Thank you! Works very nice

2022-02-19 09:20 UTC, merged